### ISSUE TITLE
Problem installing msedge-stable and msedge-canary

### ISSUE THREAD

**Issue by pixiekat** [42wim/scoop-bucket#8]
Thanks for the repository. I have no issues installing the Chrome apps in your bucket but whenever I try to install msedge-stable or msedge-canary I get an error.

`The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
URL http://msedge.f.tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/7694007e-af0e-4952-b2f9-b9e818de7d04?P1=1622782829&P2=404&P3=2&P4=iCcNVfnK6mq95BQYy5qZi5lhQyZ5UZLXw4LdOvKpb8lBim3txTkaLexyfR8dyxxCnel64aw4A6ZCE2P4siHe9g%3d%3dqg%3d%3d3d3d#/dl.7z is not valid`

This is using both Powershell and Command in Windows Terminal and regular Command Prompt.

**Comment by 42wim** [comment]
To get this to work you'll need to use my scoop fork (this can be a security risk if you don't trust the owner or don't know what the code changes do). 

```scoop config SCOOP_REPO https://github.com/42wim/scoop```

I've opened an issue about this on https://github.com/lukesampson/scoop/issues/4327
The original fix I suggested there doesn't work though and I'm now using md5 hashes for it instead of dropping the URL

**Comment by pixiekat** [comment]
Thanks, I appreciate it! I didn't notice the issue in the scoop repository but I'm following it now. 

It's not a big deal so I can wait; I just noticed it in the bucket and I wanted to move everything to scoop.
